@echo off
fnr.exe --cl --dir "%~dp0\" --fileMask "*.cfg, *.config, *.ini, *.yml" --includeSubDirectories --useRegEx --find "[abcdefghijklmnopqrstuvwxyz]:(.*?)[/\\].emulationstation[/\\]" --replace "%~dp0.emulationstation\\" --silent
FOR /f "tokens=*" %%D IN ('dir /b "%~dp0.emulationstation\Emuladores\demul*"') Do (fnr.exe --cl --dir "%~dp0\.emulationstation\\Emuladores\\%%D" --fileMask "*.cfg, *.config, *.ini, *.yml" --includeSubDirectories --useRegEx --find "[abcdefghijklmnopqrstuvwxyz]:(.*?)[/\\]demul(.*?)[/\\]" --replace "%~dp0.emulationstation\Emuladores\%%D\\" --silent)
FOR /f "tokens=*" %%D IN ('dir /b "%~dp0.emulationstation\Emuladores\dolphin*"') Do (fnr.exe --cl --dir "%~dp0\.emulationstation\\Emuladores\\%%D" --fileMask "*.cfg, *.config, *.ini, *.yml" --includeSubDirectories --useRegEx --find "[abcdefghijklmnopqrstuvwxyz]:(.*?)[/\\]dolphin(.*?)[/\\]" --replace "%~dp0.emulationstation\Emuladores\%%D\\" --silent)
FOR /f "tokens=*" %%D IN ('dir /b "%~dp0.emulationstation\Emuladores\pcsx2*"') Do (fnr.exe --cl --dir "%~dp0\.emulationstation\\Emuladores\\%%D" --fileMask "*.cfg, *.config, *.ini, *.yml" --includeSubDirectories --useRegEx --find "[abcdefghijklmnopqrstuvwxyz]:(.*?)[/\\]pcsx2(.*?)[/\\]" --replace "%~dp0.emulationstation\Emuladores\%%D\\" --silent)
FOR /f "tokens=*" %%D IN ('dir /b "%~dp0.emulationstation\Emuladores\ppsspp*"') Do (fnr.exe --cl --dir "%~dp0\.emulationstation\\Emuladores\\%%D" --fileMask "*.cfg, *.config, *.ini, *.yml" --includeSubDirectories --useRegEx --find "[abcdefghijklmnopqrstuvwxyz]:(.*?)[/\\]ppsspp(.*?)[/\\]" --replace "%~dp0.emulationstation\Emuladores\%%D\\" --silent)
FOR /f "tokens=*" %%D IN ('dir /b "%~dp0.emulationstation\Emuladores\retroarch*"') Do (fnr.exe --cl --dir "%~dp0\.emulationstation\\Emuladores\\%%D" --fileMask "*.cfg, *.config, *.ini, *.yml" --includeSubDirectories --useRegEx --find "[abcdefghijklmnopqrstuvwxyz]:(.*?)[/\\]retroarch(.*?)[/\\]" --replace "%~dp0.emulationstation\Emuladores\%%D\\" --silent)
FOR /f "tokens=*" %%D IN ('dir /b "%~dp0.emulationstation\Emuladores\cemu*"') Do (fnr.exe --cl --dir "%~dp0\.emulationstation\\Emuladores\\%%D" --fileMask "*.cfg, *.config, *.ini, *.yml" --includeSubDirectories --useRegEx --find "[abcdefghijklmnopqrstuvwxyz]:(.*?)[/\\]retroarch(.*?)[/\\]" --replace "%~dp0.emulationstation\Emuladores\%%D\\" --silent)
FOR /f "tokens=*" %%D IN ('dir /b "%~dp0.emulationstation\Emuladores\citra*"') Do (fnr.exe --cl --dir "%~dp0\.emulationstation\\Emuladores\\%%D" --fileMask "*.cfg, *.config, *.ini, *.yml" --includeSubDirectories --useRegEx --find "[abcdefghijklmnopqrstuvwxyz]:(.*?)[/\\]retroarch(.*?)[/\\]" --replace "%~dp0.emulationstation\Emuladores\%%D\\" --silent)
FOR /f "tokens=*" %%D IN ('dir /b "%~dp0.emulationstation\Emuladores\rpcs3*"') Do (fnr.exe --cl --dir "%~dp0\.emulationstation\\Emuladores\\%%D" --fileMask "*.cfg, *.config, *.ini, *.yml" --includeSubDirectories --useRegEx --find "[abcdefghijklmnopqrstuvwxyz]:(.*?)[/\\]retroarch(.*?)[/\\]" --replace "%~dp0.emulationstation\Emuladores\%%D\\" --silent)
FOR /f "tokens=*" %%D IN ('dir /b "%~dp0.emulationstation\Emuladores\xenia*"') Do (fnr.exe --cl --dir "%~dp0\.emulationstation\\Emuladores\\%%D" --fileMask "*.cfg, *.config, *.ini, *.yml" --includeSubDirectories --useRegEx --find "[abcdefghijklmnopqrstuvwxyz]:(.*?)[/\\]retroarch(.*?)[/\\]" --replace "%~dp0.emulationstation\Emuladores\%%D\\" --silent)


exit